### ISSUE TITLE
Transfer model to CasADi with library dependencies

### ISSUE THREAD

**Issue by b-mare** [pymoca/pymoca#299] opened 2023-09-22 06:49 UTC
Hi, 

I am interested in utilizing this library for the conversion of Modelica files into CasADi objects for use in optimal control strategies. My goal is to work with models that utilize MSL 4.0.0 and other custom libraries. As a first attempt to test the library I tried some examples that are already shipped with MSL4.0.0. However, I have encountered some challenges while attempting to transfer the models. Whether it's electrical, mechanical, or fluid systems, I consistently encounter parsing errors while attempting to convert and work with these models.

**Example**
```
from pymoca.backends.casadi.api import transfer_model
model = transfer_model('../example_tank_system', 'ThreeTanks',
                       {'library_folders': [f'{modelica_path}/Modelica/Library/Modelica 4.0.0/Media/Water']})
```

I get the following error

> Traceback (most recent call last):
  File "=first_example.py", line 11, in <module>
    model = transfer_model('=../example_tank_system', 'ThreeTanks',
  File "=venv_pymoca/lib/python3.10/site-packages/pymoca/backends/casadi/api.py", line 488, in transfer_model
    return _compile_model(model_folder, model_name, compiler_options)
  File "=venv_pymoca/lib/python3.10/site-packages/pymoca/backends/casadi/api.py", line 115, in _compile_model
    tree.extend(parser.parse(f.read()))
  File "venv_pymoca/lib/python3.10/site-packages/pymoca/parser.py", line 807, in parse
    parse_walker.walk(ast_listener, parse_tree)
  File "venv_pymoca/lib/python3.10/site-packages/antlr4/tree/Tree.py", line 151, in walk
    self.walk(listener, child)
  File "venv_pymoca/lib/python3.10/site-packages/antlr4/tree/Tree.py", line 151, in walk
    self.walk(listener, child)
  File "venv_pymoca/lib/python3.10/site-packages/antlr4/tree/Tree.py", line 151, in walk
    self.walk(listener, child)
  [Previous line repeated 23 more times]
  File "venv_pymoca/lib/python3.10/site-packages/antlr4/tree/Tree.py", line 152, in walk
    self.exitRule(listener, t)
  File "venv_pymoca/lib/python3.10/site-packages/antlr4/tree/Tree.py", line 167, in exitRule
    ctx.exitRule(listener)
  File "venv_pymoca/lib/python3.10/site-packages/pymoca/generated/ModelicaParser.py", line 4762, in exitRule
    listener.exitStatement_component_reference(self)
  File "venv_pymoca/lib/python3.10/site-packages/pymoca/parser.py", line 281, in exitStatement_component_reference
    right=self.ast[ctx.expression()])
KeyError: None
>
As far as I see this occurs when parsing Modelica 4.0.0/Media/Water/IF97_Utilities.mo

When I instead add the entire Modelica standard library in the library folders I get the following error
```
from pymoca.backends.casadi.api import transfer_model
model = transfer_model('../example_tank_system', 'ThreeTanks',
                       {'library_folders': [f'{modelica_path}/Modelica/Library/Modelica 4.0.0']})
```

> line 19:13 extraneous input '.' expecting {'end', '(', 'der', 'if', '+', '-', 'not', 'false', 'true', '[', '{', 'initial', IDENT, STRING, UNSIGNED_NUMBER}
line 19:19 no viable alternative at input 'sqrt(.'
line 19:66 mismatched input ')' expecting ';'
line 20:2 mismatched input 'elseif' expecting 'end'
line 22:2 mismatched input 'elseif' expecting 'end'
line 24:2 mismatched input 'else' expecting 'end'
Traceback (most recent call last):
  File "first_example.py", line 11, in <module>
    model = transfer_model('../example_tank_system', 'ThreeTanks',
  File "venv_pymoca/lib/python3.10/site-packages/pymoca/backends/casadi/api.py", line 488, in transfer_model
    return _compile_model(model_folder, model_name, compiler_options)
  File "venv_pymoca/lib/python3.10/site-packages/pymoca/backends/casadi/api.py", line 115, in _compile_model
    tree.extend(parser.parse(f.read()))
  File "venv_pymoca/lib/python3.10/site-packages/pymoca/ast.py", line 830, in extend
    self._extend(other)
  File "venv_pymoca/lib/python3.10/site-packages/pymoca/ast.py", line 710, in _extend
    for class_name in other.classes.keys():
AttributeError: 'NoneType' object has no attribute 'classes'
>

Am I doing something wrong here, or is Modelica standard language not supported? I tried several examples from multiple types of systems, but always got similar errors.

I am using

- Python 3.10.12
- antlr4-python3-runtime==4.7.2
- casadi==3.6.3
- pymoca==0.10.0
- MSL4.0.0

Nevertheless, I appreciate the effort put into developing this library and I look forward to using it with my Modelica models

Kind regards
b-mare

**Comment by jackvreeken** [comment] 2023-09-22 07:56
Yep, we're still not able to parse the entire MSL, and there are small number of known flattening issues. @kentrutan knows more about how far off we are on that front.

What you _could_ try to do is make a copy of the MSL tree, and delete all files you don't need. Pymoca isn't smart enough to skip over files it doesn't need yet, so you might be getting caught out by errors unrelated to components you're trying to use.

Next to that there is the CasADi support, which is mostly limited to what makes sense in optimal control settings. Some Modelica constructs like "algorithm" are therefore not supported. As a further aside, generally MSL components are not made with optimal control in mind, they're more suited to simulation.

Pymoca is actively being used for optimal control however, but mostly with custom libraries (not MSL). Take a look at https://gitlab.com/deltares/rtc-tools (to formulate optimal control problems), and e.g. https://gitlab.com/deltares/rtc-tools-channel-flow (for a Modelica library).

**Comment by kentrutan** [comment] 2023-09-23 10:55
@jackvreeken gave an excellent answer already. Regarding the Modelica support, approximately 10% of MSL 4.0 files fail to parse currently and there may also be flattening issues. As suggested, you may be able to minimize what is parsed and then you may still have to modify the remaining MSL code (working back and forth between a [Modelica simulation environment](https://modelica.org/tools.html) and Pymoca) to work around Pymoca shortcomings. Understanding the Pymoca issue can be challenging if you are not familiar with the inner workings of Pymoca. I'll take a quick look based on the info provided.

**Comment by kentrutan** [comment] 2023-09-23 11:49
In the first example above, the code Pymoca is choking on in `Modelica/Media/Water/IF97_Utilities.mo` is:
```modelica
        assert(p > triple.ptriple,
          "IF97 medium function boundary23ofp called with too low pressure\n"
           + "p = " + String(p) + " Pa <= " + String(triple.ptriple) +
          " Pa (triple point pressure)");
```
This is inside an algorithm section that @jackvreeken mentioned above is not well supported, even in the parser as well as the CasADi generator. The easiest work-around is to comment out this statement and any others like it in an algorithm section. The specific problem in Pymoca is that it doesn't currently support multiple arguments in the assert statement.

**Comment by kentrutan** [comment] 2023-09-23 13:46
In the second example above trying to parse the entire Modelica library, Pymoca at least provides some syntax error messages, but unfortunately doesn't give the file name. The problem is `Modelica/ComplexMath.mo`. The syntax error message says it is at line 19, column 13, which is just before the `.sqrt(`. It doesn't like the "." before the function name.

**Comment by kentrutan** [comment] 2023-09-23 15:03
> Pymoca at least provides some syntax error messages, but unfortunately doesn't give the file name.

Adding these lines to your scripts can help get file names printed out:
```python
import sys
import logging

logger = logging.getLogger("pymoca")
logger.setLevel(logging.INFO)
logging.basicConfig(stream=sys.stderr)
```

**Comment by kentrutan** [comment] 2023-09-23 15:09
I'm removing the bug label because these are really unimplemented language features vs a true bug in what we *have* implemented. The real issue is that we don't fail gracefully when there is something we don't support yet.

**Comment by kentrutan** [comment] 2023-09-26 17:43
@b-mare Thanks for taking time to report this issue. I think we have given you about all the help we can based on what you provided. 

I am closing it since there are other issues documenting known problems in parsing and flattening the MSL, never mind the output code generation. We are working to close the gaps, but we don't know when we will get to 100% of MSL parsing correctly. 

If you have more problems, then go ahead and raise another issue.

**Closed** 2023-09-26 17:45 UTC
